### PR TITLE
Setup travis, add testharness and debug playground, and fix regression for __createElement refactor

### PR DESCRIPTION
**Pull request by gwwar**
Tests now run in travis, locally in your browser, and via the command line with karma. See readme for instructions.

Tests now run all of the existing unit tests, as well as all drawing functions in the examples folder. These export tests will fail if an error is thrown or if the svg and canvas image are not [similar enough](https://github.com/Huddle/Resemble.js) to one another.

screen shot 2015-06-14 at 6 51 38 pm
screen shot 2015-06-14 at 6 51 48 pm

You can now debug issues in playground.html. See the readme for examples on how to add additional files.

screen shot 2015-06-14 at 6 56 14 pm

Before merging gliffy should create a free travis ci account and enable github permissions. You'll also want to update the travis status icon in the readme to point to your master branch.

screen shot 2015-06-14 at 7 05 16 pm

### CODE REVIEW

**Comment by gwwar** [comment]
@zenozeng as promised :saxophone: :cat2:

**Comment by zenozeng** [comment]
@gwwar  Wow, that's cool. :+1:

**Comment by clintjd** [comment]
Hi Kerry.  That would be extra special sauce awesome if you could rebase :) Thanks!

**Comment by gwwar** [comment]
@clintjd  Cool should be good to go. Just remember to update the readme to point the travis status image at the right url. You can find it by clicking on the build passing button in travis, to get this modal. Thanks for looking at all the pull requests.

screen shot 2015-06-16 at 7 18 37 pm

**Comment by clintjd** [comment]
Thanks Kerry for getting all the testing infrastructure up. Really cool!

**Comment by gwwar** [comment]
I'm glad you like it. :)

**Pull request merged**
