### PR TITLE
fixed a bug with globalAlpha

### PR DESCRIPTION
**Pull request by FuZhenn**
Hi,

At first, I would like to thanks for merging my last pull request.

This is another bugfix with globalAlpha.

### Problem:

ctx.fill() and ctx.stroke() can both set element's "opacity" attribute with globalAlpha value, so when we set globalAlpha for multiple times, opacity may be set to a wrong value.

eg:

        //draw a simple line here.
        ctx.moveTo(0,0);
        ctx.lineTo(5,5);

        ctx.globalAlpha = 1;
        //this draws the line, set its opacity to 1 and display.
        ctx.stroke();        

        ctx.globalAlpha = 0;
        //the line's opacity is set to 0 
        //which incorrectly makes the whole line transparent instead of only a transparent fill.
        ctx.fill();

### Fix:

1. when setting "stroke" or "fill", take globalAlpha into consideration.
2. instead of always setting "opacity", set "fill-opacity"  when fill() and "stroke-opacity" when stroke() seperately.

### CODE REVIEW

**Comment by webspinner** [comment]
Please add tests to test/unit.spec.js to handle the globalOpacity case.

**Comment by FuZhenn** [comment]
Sure. I will add the tests later.

**Comment by FuZhenn** [comment]
@webspinner tests of globalAlpha are added.

**Comment by webspinner** [comment]
Great @FuZhenn  thanks for your help.

**Pull request merged**
