### PR TITLE
Added ellipse command

### PR DESCRIPTION
**Pull request by CJEnright**
Canvas supports ellipses, which could be made with two arcs i guess, but
this simplifies things

### CODE REVIEW

**Comment by webspinner** [comment]
Hey @CJEnright Thanks for the contribution. Could you add a quick test case so we can catch any regressions, as described in https://github.com/gliffy/canvas2svg#add-an-example-case

**Comment by spanktar** [comment]
@CJEnright Still interested in this?

**Comment by CJEnright** [comment]
@spanktar Yeah, guess I forgot to come back to this.  I think I deleted that repo a while ago, so I opened up a [new one](https://github.com/CJEnright/canvas2svg) with test included, just let me know and we can close this request and I'll open one with the new repo.  Sorry about the confusion.

**Comment by levskaya** [comment]
While trying to use your code for rotated ellipses and rotated elliptical arcs, I noticed that your implementation ignores the "rotation" parameter as-written.  I modified your code to (1) calculate the rotated coordinates endX/Y and startX/Y and (2) to feed the rotation parameter in degrees to the SVG xAxisRotation parameter.  As far as I can tell across many test cases this properly mirrors the canvas v5 ellipse behavior.
```
   ctx.prototype.ellipse = function(x, y, radiusX, radiusY, rotation, startAngle, endAngle, counterClockwise) {
     //ellipse is the same svg command as arc, but with a radiusX and radiusY instead of just radius
       if (startAngle === endAngle) {
           return;
       }
       startAngle = startAngle % (2*Math.PI);
       endAngle = endAngle % (2*Math.PI);
       if(startAngle === endAngle) {
           endAngle = ((endAngle + (2*Math.PI)) - 0.001 * (counterClockwise ? -1 : 1)) % (2*Math.PI);
       }
       var endX = x + Math.cos(-rotation) * radiusX * Math.cos(endAngle)
                    + Math.sin(-rotation) * radiusY * Math.sin(endAngle),
           endY = y - Math.sin(-rotation) * radiusX * Math.cos(endAngle)
                    + Math.cos(-rotation) * radiusY * Math.sin(endAngle),
           startX = x + Math.cos(-rotation) * radiusX * Math.cos(startAngle)
                      + Math.sin(-rotation) * radiusY * Math.sin(startAngle),
           startY = y - Math.sin(-rotation) * radiusX * Math.cos(startAngle)
                      + Math.cos(-rotation) * radiusY * Math.sin(startAngle),
           sweepFlag = counterClockwise ? 0 : 1,
           largeArcFlag = 0,
           diff = endAngle - startAngle;

       if(diff < 0) {
           diff += 2*Math.PI;
       }

       if(counterClockwise) {
           largeArcFlag = diff > Math.PI ? 0 : 1;
       } else {
           largeArcFlag = diff > Math.PI ? 1 : 0;
       }

       this.lineTo(startX, startY);
       this.__addPathCommand(format("A {rx} {ry} {xAxisRotation} {largeArcFlag} {sweepFlag} {endX} {endY}",
           {rx:radiusX, ry:radiusY, xAxisRotation:rotation*(180/Math.PI), largeArcFlag:largeArcFlag, sweepFlag:sweepFlag, endX:endX, endY:endY}));

       this.__currentPosition = {x: endX, y: endY};
   };
```

**Comment by tiagodolphine** [comment]
Hi @spanktar do you have any plans to merge this to support ellipse ? Anything  is missing ? Just asking because this it would be useful for me and if I can help on anything that is missing.

Thanks.

**Comment by manstis** [comment]
@spanktar It would be great to have this merged.

**Comment by spanktar** [comment]
Oh, thanks for poking me! Let me get in touch with the correct folks here

**Pull request closed without merging**
